# Site
repository: taekmino/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Mintaek Oh
title: Ph.D. Candidate
lab: Autonomous Robot Intelligence Lab
department: Dept. of Civil & Environmental Engineering
university: Seoul National University
email: mintaek@snu.ac.kr
# email_title: Email (Email title override)
phone: +82-10-9079-5086
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
github_username:  taekmino
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: taekmino
linkedin_username: mintaekoh
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am Mintaek Oh, a master's student in the Department of Civil and Environmental Engineering at Seoul National University, specializing in Smart City Engineering. I am advised by [Prof. Seong-Woo Kim](https://arisnu.squarespace.com/director).
  
  Research Interests
    - **Planning**: Developing advanced path-planning algorithms for robots and autonomous systems.
    - **Control**: Researching control systems for stable and efficient robotics.
    - **Large Language Models (LLM)**: Exploring the integration of LLMs into robotics.

content:

  # Education
  - title: Education
    layout: list
    content:
      - layout: left
        type: education
        title: Seoul National University
        location: "Seoul, S.Korea"
        sub_title: M.S./Ph.D. Candidate in Department of Civil & Environmental Engineering
        caption: Mar. 2024 - Present
      - layout: left
        type: education
        title: Korea University
        location: "Seoul, S.Korea"
        sub_title: B.S. in Department of Mechanical Engineering
        caption: Mar. 2019 - Feb. 2024

  # Publications
  - title: Publications
    layout: list
    content:
      - layout: left
        type: publication-year
        year: "2025"
      - layout: left
        type: publication
        title: "Language as Cost: Proactive Hazard Mapping using VLM for Robot Navigation"
        authors: "**Mintaek Oh**, Chan Kim, and Seong-Woo Kim"
        venue: "IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), Hangzhou, China, 2025"
        additional_links:
          - title: ArXiv
            icon: fas fa-file-pdf
            url: https://arxiv.org/pdf/2508.03138
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/Taekmino/LaC
      - layout: left
        type: publication
        title: "E2Map: Experience-and-Emotion Map for Self-Reflective Robot Navigation with Language Models"
        authors: "Chan Kim*, Keonwoo Kim*, **Mintaek Oh**, Hanbi Baek, Jiyang Lee, Donghwi Jung, Soojin Woo, Younkyung Woo, John Tucker, Roya Firoozi, Seung-Woo Seo, Mac Schwager, Seong-Woo Kim"
        venue: "IEEE International Conference on Robotics and Automation (ICRA), Atlanta, USA, 2025"
        additional_links:
          - title: Homepage
            icon: fas fa-home
            url: https://e2map.github.io/
          - title: ArXiv
            icon: fas fa-file-pdf
            url: https://arxiv.org/pdf/2409.10027
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/knwoo/e2map

  # Projects
  - title: Projects
    layout: list
    content:
      - layout: left
        type: project
        title: "LIMBOv2: Indoor Humanoid Robot Using Tools"
        role: "Project Manager, System Design, Locomotion Learning, Navigation, Language Model Grounding"
        timeline: "February 2025 - Present"
        image: "images/g1.png"
        description: |
          Developed a humanoid robot equipped with tools for complex indoor tasks. The system incorporates tool usage considerations for dynamic replanning and features language-guided navigation with adaptive strategy execution based on task constraints.
      - layout: left
        type: project
        title: "LIMBO: Language-Image-based Mobile Robot"
        role: "Path Planning & Control Module Development, Virtual/Real Environment Setup"
        timeline: "February 2024 - September 2024"
        image: "images/go1.png"
        description: |
          Designed to navigate toward specified goals by following language instructions. Inspired by human emotional mechanisms, we integrate emotion into LIMBO, allowing it to adjust its behavior in a one-shot manner based on a single experience.

  # Teaching Experience
  - title: Teaching Experience
    layout: list
    content:
      - layout: left
        type: teaching
        course: "How to Make a Robot with Artificial Intelligence, Fall 2025"
        institution: "Seoul National University"
        role: "Teaching Assistant"
        images:
          - "images/final_picture_25.jpg"
          - "images/roingong25.png"
        description:
          - "Instructed ROS2 & Gazebo-based autonomous robot navigation course"
          - "Guided students to implement language-guided mobile robot navigation system with Unitree Go1 quadruped robot"
          - "Managed and organized final project competition"
        link: https://github.com/roy9852/make_ai_robot
        link_icon: fab fa-github
      - layout: left
        type: teaching
        course: "How to Make a Robot with Artificial Intelligence, Fall 2024"
        institution: "Seoul National University"
        role: "Teaching Assistant"
        images:
          - "images/final_photo_24.jpg"
          - "images/roingong24.png"
        description:
          - "Instructed ROS1 & Gazebo-based autonomous robot navigation course"
          - "Developed mission scenarios and simulation environment for language-guided robot navigation projects"
          - "Managed and organized final project competition"
        link: https://github.com/Taekmino/craip
        link_icon: fab fa-github

  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: Project name
  #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description about the work on/with the project

  # - title: Experience
  #   layout: list
  #   content:
  #     - layout: right
  #       title: Company name
  #       sub_title: Job title
  #       caption: Date Range (eg. November 2016 - present)
  #       link: Link to company (optional)
  #       quote: >
  #         Short description of the company (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description of role


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
